version: "3.9"

volumes:
  php-fpm-socket:
  db-store:
  psysh-store:


services:
  web:
    build: "./.docker/nginx"
    container_name: portfolio-nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: "./.docker/php"
    container_name: portfolio-app
    working_dir: /app
    volumes:
      - ".:/app"
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: portfolio-mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
      MYSQL_ROOT_PASSWORD: rootroot
    container_name: portfolio-mysql
